# Generated by Django 5.2.7 on 2026-08-26 19:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('total_resumes', models.PositiveIntegerField(default=0)),
                ('processed_resumes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_batches', to='jobs.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('skill_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('semantic_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('experience_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('education_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('preferred_skill_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('matched_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('missing_preferred_skills', models.JSONField(default=list)),
                ('explanation', models.TextField(blank=True)),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('recommendation', models.CharField(choices=[('Highly Recommended', 'Highly Recommended'), ('Recommended', 'Recommended'), ('Consider', 'Consider'), ('Not Recommended', 'Not Recommended')], max_length=30)),
                ('status', models.CharField(choices=[('new', 'New'), ('screened', 'Screened'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='new', max_length=20)),
                ('screened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_results', to='resumes.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_results', to='jobs.job')),
                ('screened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Screening Result',
                'verbose_name_plural': 'Screening Results',
                'ordering': ['-overall_score', '-screened_at'],
                'indexes': [models.Index(fields=['job', '-overall_score'], name='screening_s_job_id_17a236_idx'), models.Index(fields=['candidate', '-screened_at'], name='screening_s_candida_4528c4_idx'), models.Index(fields=['recommendation'], name='screening_s_recomme_28a8d2_idx'), models.Index(fields=['status'], name='screening_s_status_37e6f7_idx')],
                'unique_together': {('candidate', 'job')},
            },
        ),
    ]
